### ISSUE TITLE
Add sql backend support for updating variable metadata

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/datamart-api#103]
See Issue #102 for context

Add sql backend support for updating variable metadata. The exist metadata field edges should be deleted before inserting new edges.

**Comment by zmbq** [comment]
There is a function in dal.py called delete_variable_metadata . Originally it has deleted all the variable metadata of a given variable qnode. I've changed it so that it accepts a `labels=[....]` array. Pass the labels you want to delete, and only those edges are going to be deleted.

If labels are not passed, everything is deleted.

It is in the `development` branch.

**Comment by kyao** [comment]
Done
