### ISSUE TITLE
Countr and Region columns blank

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/datamart-api#97]
Country and admin1 columns are not properly returned. They are both blank.

The tar file contains the annotated excel and the kgtk edge files.
[price.tar.gz](https://github.com/usc-isi-i2/datamart-api/files/5479301/price.tar.gz)

**Comment by kyao** [comment]
Sample get command:

```
get('http://localhost:12543/datasets/KW-part/variables/price')

dataset_id,variable_id,variable,main_subject,main_subject_id,value,value_unit,time,time_precision,country,admin1,admin2,admin3,region_coordinate,stated_in,stated_in_id,Datasource,Market,Price_Type,located in the administrative territorial entity,stated in
KW-part,price,Commodity Price,Commodity Exchange rate,QQKW_part_Commodity_Exchange_rate,19.36,ETB per USD,2014-04-01T00:00:00Z,month,,,,,,,,LCU,,,,
KW-part,price,Commodity Price,Commodity Exchange rate,QQKW_part_Commodity_Exchange_rate,19.36,ETB per USD,2014-04-01T00:00:00Z,month,,,,,,,,LCU,,,,
KW-part,price,Commodity Price,Commodity Exchange rate,QQKW_part_Commodity_Exchange_rate,19.43,ETB per USD,2014-05-01T00:00:00Z,month,,,,,,,,LCU,,,,
KW-part,price,Commodity Price,Commodity Exchange rate,QQKW_part_Commodity_Exchange_rate,19.43,ETB per USD,2014-05-01T00:00:00Z,month,,,,,,,,LCU,,,,
KW-part,price,Commodity Price,Commodity Exchange rate,QQKW_part_Commodity_Exchange_rate,19.5,ETB per USD,2014-06-01T00:00:00Z,month,,,,,,,,LCU,,,,
```

**Comment by kyao** [comment]
@zmbq Looks like changing this line fixes the bug. Not sure why the bug is happening now. 

From:
https://github.com/usc-isi-i2/datamart-api/blob/7354e644cce3b5ac6177102f2a3a7924521393c6/db/sql/dal/variables.py#L27
to 
```
if self.data_type == 'location' and (not self.name or self.name == 'located in the administrative territorial entity'):
```

**Comment by zmbq** [comment]
We have defined a strict heuristic of determining whether a qualifier is the location qualifier. It has to have one of the location labels (P17, P2006190000?, P131) and has no name. Otherwise, the specified qualifier name takes precedence. If the qualifier is called location, it is always used as a location, regardless of the label.

So I think the easiest thing is to change the qualifier in the metadata - call it location and not 'located in the administrative territorial entity'). Or we can add a list of qualifier names that should be interpreted as location.

**Comment by kyao** [comment]
Changing the metadata sounds reasonable. Where are we defining this metadata?

**Comment by saggu** [comment]
edge type should take precedence over the qualifier name @zmbq

**Comment by zmbq** [comment]
Fixed in development, please try it.

**Comment by kyao** [comment]
Tested
